finDataMake: Date.cpp fin_data.cpp fin_data_test.cpp finManager.cpp
	g++ -Wall -std=c++0x Date.cpp fin_data.cpp finManager.cpp finManager_test.cpp -o test

dateMake: Date.cpp date_test.cpp
	g++ -Wall -std=c++0x Date.cpp date_test.cpp -o test

stableMake: Date.cpp fin_data.cpp finManager.cpp finAid.cpp
	g++ -Wall -std=c++0x Date.cpp fin_data.cpp finManager.cpp finAid.cpp -o finAid
